/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppPlayRouteImport } from './routes/_app.play'
import { Route as AppMarketRouteImport } from './routes/_app.market'
import { Route as AppGrimoireRouteImport } from './routes/_app.grimoire'
import { Route as AppBattleRouteImport } from './routes/_app.battle'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppPlayRoute = AppPlayRouteImport.update({
  id: '/play',
  path: '/play',
  getParentRoute: () => AppRoute,
} as any)
const AppMarketRoute = AppMarketRouteImport.update({
  id: '/market',
  path: '/market',
  getParentRoute: () => AppRoute,
} as any)
const AppGrimoireRoute = AppGrimoireRouteImport.update({
  id: '/grimoire',
  path: '/grimoire',
  getParentRoute: () => AppRoute,
} as any)
const AppBattleRoute = AppBattleRouteImport.update({
  id: '/battle',
  path: '/battle',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/battle': typeof AppBattleRoute
  '/grimoire': typeof AppGrimoireRoute
  '/market': typeof AppMarketRoute
  '/play': typeof AppPlayRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/battle': typeof AppBattleRoute
  '/grimoire': typeof AppGrimoireRoute
  '/market': typeof AppMarketRoute
  '/play': typeof AppPlayRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/battle': typeof AppBattleRoute
  '/_app/grimoire': typeof AppGrimoireRoute
  '/_app/market': typeof AppMarketRoute
  '/_app/play': typeof AppPlayRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/battle' | '/grimoire' | '/market' | '/play'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/battle' | '/grimoire' | '/market' | '/play'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/battle'
    | '/_app/grimoire'
    | '/_app/market'
    | '/_app/play'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/play': {
      id: '/_app/play'
      path: '/play'
      fullPath: '/play'
      preLoaderRoute: typeof AppPlayRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/market': {
      id: '/_app/market'
      path: '/market'
      fullPath: '/market'
      preLoaderRoute: typeof AppMarketRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/grimoire': {
      id: '/_app/grimoire'
      path: '/grimoire'
      fullPath: '/grimoire'
      preLoaderRoute: typeof AppGrimoireRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/battle': {
      id: '/_app/battle'
      path: '/battle'
      fullPath: '/battle'
      preLoaderRoute: typeof AppBattleRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppBattleRoute: typeof AppBattleRoute
  AppGrimoireRoute: typeof AppGrimoireRoute
  AppMarketRoute: typeof AppMarketRoute
  AppPlayRoute: typeof AppPlayRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppBattleRoute: AppBattleRoute,
  AppGrimoireRoute: AppGrimoireRoute,
  AppMarketRoute: AppMarketRoute,
  AppPlayRoute: AppPlayRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
